site_name: MosaiCatcher documentation
site_description: A Snakemake-based workflow for quality control and detection of SV in Strand-Seq sequencing data
theme: material
# palette:
#   primary: black
#   accent: black
nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
