site_name: MosaiCatcher documentation
site_description: A Snakemake-based workflow for quality control and detection of SV in Strand-Seq sequencing data
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - header.autohide

  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/friendsofstrandseq/mosaicatcher-pipeline
repo_name: friendsofstrandseq/mosaicatcher-pipeline

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started:
      - Quick Start: quickstart.md
      - Input Data Formats: input-data.md
  - Running the Pipeline:
      - Usage: usage.md
      - Parameters: parameters.md
      - Advanced Modes: advanced-modes.md
      - EMBL HPC: embl.md
  - Reference:
      - Pipeline Outputs: outputs.md
      - Reference Genomes: reference-genomes.md
      - Reproduce publication results: publication.md
      - Development Roadmap: roadmap.md
      - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; 2022 - 2026 Thomas Weber

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/friendsofstrandseq/mosaicatcher-pipeline
      name: GitHub

  version:
    provider: mike
